constants:
  input_channels: 3
  n_classes: 0
  image_size: 128

latent_diffusion: True

dataset:
  _target_:  utils.CASIA_dataset.SamplesWithEmbeddingsFileDataset
  samples_root: "../../../../dataset/CASIA/images" # The root path is the location where the log file is located
  embeddings_file_path: "../../../../dataset/CASIA/elasticface_embeddings/elastic_embed.npy" # The root path is the location where the log file is located
  images_name_file_path: "../../../../dataset/CASIA/elasticface_embeddings/image_names.pkl" # The root path is the location where the log file is located
  sample_file_ending: ".jpg"
  sample_loader:
    _target_: utils.CASIA_dataset.PILImageLoader
  sample_transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size:
        - 128
        - 128
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.RandomHorizontalFlip
        p: 0.5
                                                   
